### ISSUE TITLE
Rendering to Netlify Can't Compile CSS for Timeline Menu

### ISSUE THREAD

**Issue by dedi0003** [s4n7h0/hugo-theme-timeline#1]
I love this theme hence try to make a new blog using it. I can render it perfectly in local computer shown in image below. 
<img src = "https://i.imgur.com/8zF4IH8.jpg" width = 50%>

However, when I deploy public folder on netlify it can only render the main page. The second page (timeline menu) is not rendered with style. 
<img src = "https://i.imgur.com/NoL4Aku.jpg" width = 50%>
 
I believe that I need to modify something in config.toml since previously I failed to render the main page but then changed `baseURL = "/"`  to make it worked.

As information I put these codes in **config.toml**  
`baseURL = "/"`
`[menu]
  [[menu.main]]
    identifier = "timeline"
    name       = "timeline"
    url        = "timeline/"
    weight     = 1`

Any suggestion would be really appreciated

**Comment by s4n7h0** [comment]
Hi @dedi0003, Glad to know you liked the theme and considering to use it for your website. 
Your `config.toml` looks okay. I'm using the same for my personal website, i.e., `baseURL = "/"` and it should render properly. Could you see inspect the browser (using dev tools) and see which URLs are failing. The issue looks like broken links in loading the static files.

**Comment by dedi0003** [comment]
> Could you see inspect the browser (using dev tools) and see which URLs are failing. The issue looks like broken links in loading the static files.  

Hi Sanoop, thanks for your response. After I checked using devtools, the result is as follows:
<img src = "https://i.imgur.com/ZZ3IxM8.png" width = 80%>

The css and js file failed to be load.

<img src = "https://i.imgur.com/ezOw1gD.png" width = 80%>

**Comment by s4n7h0** [comment]
Hi @dedi0003, I see the static files are referencing to example.com, not to your specific site. Consider changing the base URL in the config to your domain or change it to `"/"`.  This should ideally resolve the problem. Let me know if you get it working.

**Comment by dedi0003** [comment]
> Hi @dedi0003, I see the static files are referencing to example.com, not to your specific site. Consider changing the base URL in the config to your domain or change it to `"/"`. This should ideally resolve the problem. Let me know if you get it working.

Hi Sanoop, actually it was after changed ```baseUrl = "/"```.  The main page can be rendered neatly, but when I enter second page (the timeline menu) it was broken.  
Hence I guess it might be something in the timeline config ```[menu] [[menu.main]] identifier = "timeline" name = "timeline" url = "timeline/" weight = 1```, I tried to modify it but nothing happened. Is there any configuration that specific for the timeline menu (secondary page)?

My hosted blog with this theme is at [netlify](https://tender-wescoff-685f04.netlify.app/)

**Comment by s4n7h0** [comment]
The timeline URL is just the relative one. So just `timeline/` should work there. The main page is taking proper base URL, but the timeline page is still taking example.com from the template. Try to do a clean build again, in case if any caching issues with netlify.

**Comment by dedi0003** [comment]
Dear Sanoop, after I redownload your theme manualy it finally works! Previously I downloaded using blogdown R through RStudio. Thank you for creating this awesome theme! My last question before I close this issue; how can I add other header menu (not only timeline) just like on your website?

**Comment by s4n7h0** [comment]
Great to know it worked for you. To create other pages, you would need to create new layouts and change the config file to add respective menu. Please look into the hugo documentation - https://gohugo.io/getting-started/quick-start/

**Comment by dedi0003** [comment]
> Great to know it worked for you. To create other pages, you would need to create new layouts and change the config file to add respective menu. Please look into the hugo documentation - https://gohugo.io/getting-started/quick-start/

Okay thanks for the info I will try that. Cheers!
