### ISSUE TITLE
Add Css and Js files

### ISSUE THREAD

**Issue by gibranlp** [s4n7h0/hugo-theme-timeline#6]
Hi,

First of all this theme is awesome, thank you for it.

I'm having some issues with some new files Css and Js that i'm adding, i have added them in the static/css and static/js folder respectively and for the index page they work fine, but then i realized that if i go into the timeline i no longer get access to those files so i added them again into the timeline folder and then the timeline works fine, but when i enter any post i no longer get access to those css and js files again, apparently the theme is looking for those files inside a folder with the name of the post, something like this (https://helgen.gibranlp.dev/timeline/amet_mauris/js/bootstrap-hover-dropdown.js), i'm fairly new to hugo is there a way i can make the entire theme read the new css and js files only from one location?

Cheers

**Comment by s4n7h0** [comment]
@gibranlp can you try giving the absolute path or use begin with a backslash for the static file paths.

**Comment by gibranlp** [comment]
I have tried everything it's like if the files are not in the folder next to everything all i get is http://localhost:1313/timeline/js/jquery.min.js Can not be found. Do you have any other ideas of what could be happening?

**Comment by gibranlp** [comment]
Ad just as an addon comment happens with fonts, images, css and js files basically everything

**Comment by s4n7h0** [comment]
@gibranlp This must be some silly path issue. Do you have the code published on github I can take a look ? Also can you double check the static files are within the theme folder itself and not outside the theme folder ?

**Comment by gibranlp** [comment]
i just added you to the repository, thanks for the help

**Comment by gibranlp** [comment]
Hey Sorry i had already fix the issue thank you.
